### ISSUE TITLE
Get tx detail given his exstrinsic hash

### ISSUE THREAD

**Issue by roccomuso** [polkascan/substrate-interface-api#3]
I would like to get a transaction by his id (extrinsic hash), using rpc.

This is the tx I'm trying to get (https://polkadot.subscan.io/extrinsic/0x6213f421bd096ca554ac6813009467f326a07bcaa411e726ea4c5c86dd0e5b06) but I do get a 500 internal error with a request like:

```json
{
    "jsonrpc":"2.0",
    "method":"runtime_getState",
    "params":[
        "System",
        "Events",
        [],
        "0x6213f421bd096ca554ac6813009467f326a07bcaa411e726ea4c5c86dd0e5b06"
        ],
    "id":4
}
```

Is it the right rpc method?
Any hints?

**Comment by arjanz** [comment]
The RPC method you tried is to return the events occurred for given block hash, so providing an extrinsic hash will not give any result. There is no index or RPC call to fetch this directly, using the API of one of the block explorers is a way to retrieve this e.g. https://explorer-31.polkascan.io/polkadot/api/v1/extrinsic/0x6213f421bd096ca554ac6813009467f326a07bcaa411e726ea4c5c86dd0e5b06?include=events

**Comment by roccomuso** [comment]
Is that API powered by https://github.com/polkascan/polkascan-pre-explorer-api ?

**Comment by arjanz** [comment]
Yes polkascan.io is the hosted version of our Github repository
