### ISSUE TITLE
Support tip and era in runtime_createSignaturePayload API

### ISSUE THREAD

**Issue by gutenye** [polkascan/substrate-interface-api#4]
Hey guys

The `runtime_createSignaturePayload` API does not support custom `tip` and `era`. `tip` is a fee to make the tx higher priority, it would be very useful.

**Comment by arjanz** [comment]
The library supports it (https://github.com/polkascan/py-substrate-interface/blob/5c6dd994ec3a253915f252dc3ffe916934b11e98/substrateinterface/__init__.py#L1277) but is indeed missing in the API application. It should be a small effort to add this..

**Comment by arjanz** [comment]
It was indeed not much work :) You can check out the latest version of https://github.com/polkascan/substrate-interface with reference GUI how to use the era and tip

**Comment by gutenye** [comment]
Thank you very much!
